<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Ltx.Core/Ltx.Core.csproj" />
    <ProjectReference Include="../../src/Ltx.Media/Ltx.Media.csproj" />
    <ProjectReference Include="../../src/Ltx.SafeTensors/Ltx.SafeTensors.csproj" />
  </ItemGroup>
</Project>
